routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('login', 'HomeController@index')->name('login');
Route::post('login', 'HomeController@doLogin')->name('login');
Route::get('logout', 'HomeController@logout')->name('logout');
Route::get('register', 'HomeController@register')->name('register');
Route::post('register', 'HomeController@doRegister')->name('register');
Route::get('verify_account/{token}', 'HomeController@verifyAccount')->name('verify_account');

Route::group(["middleware" => "CheckLogin"], function (){
    Route::get('/', 'ContactController@index')->name('home');
    Route::get('delete/{id}', 'ContactController@destroy')->name('contact.delete');
    Route::resource('contact', 'ContactController');

    Route::get('search', 'ContactController@search')->name('contact.search');
});

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'created_by', 'first_name', 'middle_name', 'last_name', 'email', 'phone_primary', 'phone_secondary', 'profile_image'
    ];

    /**
     * relationship with table user
     *
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'id', 'created_by');
    }

    /**
     * relationship with table user
     *
     */
    public function shared() {
        return $this->hasMany(ShareContact::class, 'contact_id', 'id');
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ContactRequest;

use App\ContactManager\Contact\ContactInterface;
use Auth;

class ContactController extends Controller
{
    public $repoContact;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(ContactInterface $repoContact) {
        $this->repoContact = $repoContact;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return view('welcome');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request) {
        $contacts = $this->repoContact->getContacts(Auth::id(), $request->search)->sortBy('first_name');
        return view('contacts.listing', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $contact = null;
        return view('contacts.create', compact('contact'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\ContactRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContactRequest $request, ContactInterface $repoContact) {
        if( $repoContact->saveContact($request) ) {
            return redirect()->route('home')->with('success', 'Contact '.((empty($request->id)) ? 'created' : 'updated').' successfully');
        } else {
            return redirect()->back()->with('error', 'Error while saving contact. Try again later.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
            $id = decrypt($id);
            $contact = $this->repoContact->findContact($id);
            return view('contacts.create', compact('contact'));
        } catch(\Exception $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        if($this->repoContact->delete($id)) {
            return redirect()->back()->with('success', 'Contact deleted successfully!');
        } else {
            return redirect()->back()->with('error', 'Error while deleting contact. Please try again.');
        }
    }
}

resources/views/contacts/create.blade.php
@extends('layouts.app')

@section('header_styles')
@stop

@section('content')
<div class="container theme-showcase" role="main">
      <div class="page-header">
        <h3 class="form-signin-heading">@if(empty($contact['id'])) Create @else Edit @endif Contact</h3>
      </div>

      @include('alertMessage')
      
      {!! Form::model($contact, ['route' => 'contact.store','id' => 'form', 'class'=>'form-signin', 'method'=> 'POST', 'files' => true]) !!}
        {{ csrf_field() }}
        {!! Form::hidden('id', null) !!}
        {!! Form::hidden('created_by', \Auth::id()) !!}
        <div class="row">
          <div class="form-group col-md-4">
            <label for="first_name" class="">First Name*</label>
            {!! Form::text('first_name',null,['class' => 'form-control','placeholder' => 'Enter First Name', 'id' => 'first_name', 'required'=>'required', 'autofocus' => 'autofocus']) !!}
          </div>
          <div class="form-group col-md-4">
            <label for="middle_name" class="">Middle Name</label>
            {!! Form::text('middle_name',null,['class' => 'form-control','placeholder' => 'Enter Middle Name', 'id' => 'middle_name']) !!}
          </div>
          <div class="form-group col-md-4">
            <label for="last_name" class="">Last Name*</label>
            {!! Form::text('last_name',null,['class' => 'form-control','placeholder' => 'Enter Last Name', 'id' => 'last_name', 'required'=>'required']) !!}
          </div>
        </div>

        <div class="row">
          <div class="form-group col-md-4">
            <label for="phone_primary" class="">Primary Phone*</label>
            {!! Form::text('phone_primary',null,['class' => 'form-control','placeholder' => 'Enter Primary Phone', 'id' => 'phone_primary', 'required'=>'required']) !!}
          </div>
          <div class="form-group col-md-4">
            <label for="phone_secondary" class="">Secondary Phone</label>
            {!! Form::text('phone_secondary',null,['class' => 'form-control','placeholder' => 'Enter Secondary Phone', 'id' => 'phone_secondary']) !!}
          </div>
          <div class="form-group col-md-4">
            <label for="email" class="">Email Address*</label>
            {!! Form::email('email',null,['class' => 'form-control','placeholder' => 'Enter Email', 'id' => 'email', 'required'=>'required']) !!}
          </div>
        </div>
        
        <div class="row">
          <div class="form-group col-md-6">
            <label>Contact image/photo</label>
            <div class="row">
              <div class="col-md-3">
                @if(empty($contact->id))
                  <img class="img-thumbnail" alt="200x200" data-holder-rendered="true" src="{{asset(config('constants.DEFAULT_PROFILE_IMAGE'))}}" />
                @else
                  @if(empty($contact->profile_image))
                      <img class="img-thumbnail" alt="200x200" data-holder-rendered="true" src="{{asset(config('constants.DEFAULT_PROFILE_IMAGE'))}}" />
                  @else
                      <img class="img-thumbnail" alt="200x200" data-holder-rendered="true" src="{{asset($contact->profile_image)}}" />
                  @endif
                @endif
              </div>
              <div class="col-md-9">
              <input name="profile_image" type="file" id="profile_image">
              <p class="text-info">
                Only jpeg,jpg,png,gif files are allowed. <br>Max file size should be 10MB.
              </p>
              </div>
            </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 float-right text-right">
              <button class="btn btn-sm btn-primary" type="submit">{{ (empty($contact->id) ? 'Create' : 'Update')}} Contact</button>
              <a href="{{url()->previous()}}" class="btn btn-sm btn-default" >Cancel</a>
            </div>
        </div>
    
        

      {!! Form::close() !!}
      </div>



    </div> <!-- /container -->

@stop

@section('footer_scripts')
@stop

resources/views/contacts/listing.blade.php
@if($contacts->count() > 0)
      <div class="row">
        @foreach($contacts as $contact)
            <div class="col-sm-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{$contact->first_name}} {{$contact->middle_name}} {{$contact->last_name}}</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-4">
                                @if(empty($contact->profile_image))
                                    <img class="img-thumbnail" alt="200x200" data-holder-rendered="true" src="{{asset(config('constants.DEFAULT_PROFILE_IMAGE'))}}" />
                                @else
                                    <img class="img-thumbnail" alt="200x200" data-holder-rendered="true" src="{{asset($contact->profile_image)}}" />
                                @endif
                            </div>
                            <div class="col-md-8" style="padding-left:0">
                                <p>
                                    <label>Primary: </label> {{$contact->phone_primary}}
                                    <br>
                                    <label>Secondary: </label> {{$contact->phone_secondary}}
                                    <br>
                                    <label>Email: </label> 
                                    {{(strlen($contact->email)>20) ? substr($contact->email, 0, 20).'...' : $contact->email}}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer text-right">
                        <a href="javascript:;" class="pull-left">0 shares</a>
                        <a href="{{route('contact.edit', [encrypt($contact->id)])}}" class="btn btn-xs btn-primary"><i class="fa fa-pencil-alt"></i></a>
                        <a href="#" class="btn btn-xs btn-default"><i class="fa fa-share-alt"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-danger deleteContact" data-href="{{route('contact.delete', [$contact->id]) }}"><i class="fa fa-trash"></i></a>
                    </div>
                </div>
            </div>
        @endforeach
        </div>
        
      </div>
    @else
        <div class="row">
            <div class="col-md-12 text-center">
            <div class="panel panel-default" style="padding: 20px 0;">
                <i class="fa fa-bell fa-3x"></i><br>
                
                <h3>No contacts found. </h3>
                <a href="{{url('contact/create')}}" class="btn btn-link" style="font-size:16px;">Add New Contact</a>
                </div>
            </div>
        </div>
    @endif